config/routes.rb
StatsExpose::Application.routes.draw do

  resources :dashboards do
    member do
      post "updateorder"
    end
    resource :widgets
  end

  

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_many :widgets
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :dashboard

  CHART_TYPE = {
      :map => "Mappa",
      :AreaChart => "Area chart",
      :PieChart => "Pie Chart",
      :ColumnChart => "Column chart",
      :LineChart => "Line chart",
      :Table => "Table",
      :BarChart => "Bar chart"
  }

  SIZES = {
      'col-md-6' => '50%',
      'col-md-12' => '100%'
  }

  ENDPOINTS = {
      'Popolazione per quartiere su X anni' => 'http://pws0000461.lugano.ch:3131/demographics?indicator[method]=total_by_year_quartiere&indicator[quartiere_id]=1&indicator[from]=1999&indicator[to]=2012',
      'Totale annuo' => 'http://pws0000461.lugano.ch:3131/demographics?indicator[method]=totale_quartieri_anno&indicator[year]=2012',
      'Totale attuale' => 'http://pws0000461.lugano.ch:3131/demographics?indicator[method]=totale_abitanti'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :null_session
   before_filter :allow_cross_domain_access
   def allow_cross_domain_access

     headers["Access-Control-Allow-Origin"] = "*"
     headers["Access-Control-Allow-Methods"] = %w{GET POST PUT DELETE}.join(",")
     headers["Access-Control-Allow-Headers"] = %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(",")
     head(:ok) if request.request_method == "OPTIONS"
   end


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @dashboards = Dashboard.all

    #render :json => @dashboards

    respond_to do |format|
      format.html
      format.json { render json: @dashboards }
    end

  end

  def show
    @dashboard = Dashboard.find((params[:id]))
    @widgets1 = @dashboard.widgets.order("sequence")
    @widget = Widget.new

    json_dash = Hash.new

    json_dash[:id] = @dashboard.id
    json_dash[:widgets] = @widgets1

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: json_dash }
    end

  end


  def updateorder
    @dashboard = Dashboard.find((params[:id]))
    print params

    params[:item].each_index do |index|
      widget = @dashboard.widgets.find(params[:item][index])
      widget.sequence=index
      widget.save
    end

    render :inline => ""
  end


  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard: '+@dashboard.title+' was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dashboard
    @dashboard = Dashboard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dashboard_params
    params.require(:dashboard).permit(:title)
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    tmp_params = widget_params
    dashboard = Dashboard.find(params[:dashboard_id])
    tmp_params[:dashboard_id]=dashboard.id
    tmp_params[:sequence]=dashboard.widgets.length

    @widget = Widget.new(tmp_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to dashboard, notice: 'Widget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @widget }
      else
        format.html { render action: 'new' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:dashboard_id, :sequence, :content, :size, :endpoint, :chart_type, :title, :indicator, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def widget_box(widget)
    if (widget.chart_type == "map") then
      render(:partial => 'widgets/widget_map',locals: {id: widget.id, size: widget.size}).to_s

    else
      render(:partial => 'widgets/widget_chart',
             locals: {id: widget.id, size: widget.size,endpoint: widget.endpoint,chart_type: widget.chart_type,title: widget.title, indicator: widget.indicator}).to_s
    end

  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard,:html => { :class =>"form-horizontal"}) do |f| %>
    <% if @dashboard.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

          <ul>
            <% @dashboard.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <label class="col-md-2 control-label"><%= f.label :title %><br></label>
      <div class="col-md-10">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>



<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>
<hr />
<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

<%= render 'form' %>

app/views/dashboards/index.html.erb
<h1>Listing dashboards</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= dashboard.title %></td>
        <td><span class="glyphicon glyphicon-eye-open"></span><%= link_to 'Show', dashboard %></td>
        <td><span class="glyphicon glyphicon-pencil"></span><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
        <td><span class="glyphicon glyphicon-trash"></span><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Dashboard', new_dashboard_path %>

app/views/dashboards/new.html.erb
<%= link_to t(:back), dashboards_path %>
<h1>New dashboard</h1>

<%= render 'form' %>

app/views/dashboards/show.html.erb
<div id="wrapper" class="row" data-url="<%= dashboard_path(@dashboard)%>">
  <% if notice != nil %><div id="notice" class="col-md-12 bs-callout bs-callout-info"><%= notice %></div><% end %>
  <h1><%= @dashboard.title %></h1>
  <div id="action-bar">
    <div class="col-md-6">
      <a data-toggle="modal" href="#myModal">
        <button type="button" class="btn btn-primary">
          <span class="glyphicon glyphicon-plus"></span> Add widget
        </button>
      </a>
    </div>
    <div class="col-md-6" style="text-align: right;">
      <button type="button" id="sort_toggle" class="btn btn-warning">
        <span id="pin_sortable" class="glyphicon glyphicon-pushpin" style="display: none;"></span> Block widgets
      </button>
    </div>
  </div>
  <br />
  <hr />
  <ul id="sortable1" class="widget-list">
    <% @widgets1.each do |widget| %>
       <%= raw widget_box(widget) %>
    <% end %>
  </ul>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= render "widgets/form" %>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StatsExpose</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>

  <%= stylesheet_link_tag 'http://js.arcgis.com/3.6/js/esri/css/esri.css' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js' %>
  <%= javascript_include_tag 'http://code.angularjs.org/1.0.8/angular-resource.min.js' %>
  <%= javascript_include_tag 'http://js.arcgis.com/3.6/' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		  <span class="sr-only">Toggle navigation</span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="<%= dashboards_path %>">Stats Dashboard</a>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
		  <li class="active"><a href="/pure.html">Pure</a></li>
		  <li><a href="#">Link</a></li>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
			<ul class="dropdown-menu">
			  <li><a href="#">Action</a></li>
			  <li><a href="#">Another action</a></li>
			  <li><a href="#">Something else here</a></li>
			  <li><a href="#">Separated link</a></li>
			  <li><a href="#">One more separated link</a></li>
			</ul>
		  </li>
		</ul>
	   
	  </div><!-- /.navbar-collapse -->
	</nav>
	
			<div class="container">  
		<%= yield %>

		  <footer>
			<p>&copy; Company 2013</p>
		  </footer>

		</div><!--/.fluid-container-->

    <script>
        dojo.require("esri.map");
        dojo.require("esri.layers.FeatureLayer");
        dojo.addOnLoad(function() {
            angular.bootstrap(document, ['mapApp']);
        });
    </script>
</body>
</html>

app/views/widgets/_form.html.erb
<%= form_for([@dashboard, @widget]) do |f| %>
    <% if @widget.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

          <ul>
            <% @widget.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label "Indicatore" %><br>
      <%= select :widget,:endpoint, options_for_select(Widget::ENDPOINTS.map {|k,v| [ k, v ] }) %>
    </div>
    <div class="field">
      <%= f.label "Tipo di grafico" %><br>
      <%= select :widget,:chart_type, options_for_select(Widget::CHART_TYPE.map {|k,v| [ v, k ] }) %>
    </div>
    <div class="field">
      <%= f.label :size %><br>
      <%= select :widget,:size, options_for_select(Widget::SIZES.map {|k,v| [ v, k ] }) %>
    </div>
    <div class="field">
      <%= f.label "Titolo del widget" %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label "Titolo del widget" %><br>
      <%= f.text_area :description %>
    </div>

    <div class="modal-footer">
      <%= f.submit :class => "btn btn-primary" %>

    </div>
<% end %>

app/views/widgets/_widget_chart.html.erb
<script>
    function GreetingCtrl<%= id %>($scope, $http) {

        $scope.chart = {
            "type": "<%= chart_type %>",
            "displayed": true,
            "cssStyle": "height:400px; width:100%;",
            "options": {
                "title": "<%= title %>",
                "isStacked": "true",
                "fill": 20,
                "displayExactValues": true,
                "vAxis": {
                    "title": "Popolazione",
                    "gridlines": {
                        "count": 10
                    }
                },
                "hAxis": {
                    "title": "Anno"
                }
            },
            "formatters": {}
        }

        $http.get("<%= endpoint %>").success(function(data) {
            $scope.chart.data = data;
        });

    }
</script>


  <li ng-controller="GreetingCtrl<%= id %>" id="item-<%= id %>" class="<%= size %>">
    <div class="frame">
      <div class="chart">
        <div google-chart chart="chart" type="AreaChart" titlex="Popolazione" titley="Anno" style="{{chart.cssStyle}}" />
      </div>
    </div>
  </li>

app/views/widgets/_widget_map.html.erb
<li id="item-<%= id %>" class="<%= size %>"><div class="frame">

<map>
  <dynamic-layer url="http://srvgists006.lugano.ch:6080/arcgis/rest/services/Basemap/BaseMapDyn/MapServer"></dynamic-layer>
  <feature-layer url="http://srvgists006.lugano.ch:6080/arcgis/rest/services/Basemap/Quartieri/FeatureServer/0"></feature-layer>
</map>
</div></li>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Dashboard</th>
      <th>Sequence</th>
      <th>Content</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.dashboard %></td>
        <td><%= widget.sequence %></td>
        <td><%= widget.content %></td>
        <td><%= widget.size %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dashboard:</strong>
  <%= @widget.dashboard %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @widget.sequence %>
</p>

<p>
  <strong>Content:</strong>
  <%= @widget.content %>
</p>

<p>
  <strong>Size:</strong>
  <%= @widget.size %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>